name: React CI + EC2 Deploy

on:
  push:
    branches: [main]

jobs:
# ────────────────────────── ① 로컬-CI 빌드 ──────────────────────────
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20            # 필요 버전
          cache: yarn                 # yarn.lock 기반 캐시

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Build (Vite)
        run: yarn build               # dist/ 생성

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist                  # 폴더 전체 업로드

# ────────────────────────── ② EC2 배포 ──────────────────────────
  deploy:
    needs: build                      # 빌드가 성공해야만 실행
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist

      # dist → EC2 (증분 복사)
      - name: Copy dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER || 'ubuntu' }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: dist/
          target: /home/ubuntu/react-app/
          rm: true                    # target 쪽 기존 파일 삭제 후 동기화

      # Nginx 가볍게 reload
      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER || 'ubuntu' }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: sudo systemctl reload nginx
