name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Remote deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          APP_DIR=/home/ubuntu/react-app

          # 처음이면 레포 클론
          if [ ! -d "$APP_DIR/.git" ]; then
            git clone https://github.com/${{ github.repository }} $APP_DIR
          fi

          cd $APP_DIR
          git fetch --all
          git reset --hard origin/${GITHUB_REF_NAME}

          yarn --frozen-lockfile   # 의존성
          yarn build              # dist/ 생성

          sudo systemctl reload nginx
